#!/bin/bash

BASE="100-days-of-devops"

mkdir -p "$BASE"

files=(
"day-3-secure-root-ssh-access.md"
"day-4-script-execution-permissions.md"
"day-5-selinux-installation-and-configuration.md"
"day-6-create-a-cron-job.md"
"day-7-linux-ssh-authentication.md"
"day-8-install-ansible.md"
"day-9-mariadb-troubleshooting.md"
"day-10-linux-bash-scripts.md"
"day-11-install-and-configure-tomcat-server.md"
"day-12-linux-network-services.md"
"day-13-iptables-installation-and-configuration.md"
"day-14-linux-process-troubleshooting.md"
"day-15-setup-ssl-for-nginx.md"
"day-16-install-and-configure-nginx-as-an-lbr.md"
"day-17-install-and-configure-postgresql.md"
"day-18-install-and-configure-db-server.md"
"day-19-install-and-configure-web-application.md"
"day-20-configure-nginx-and-php-fpm-using-unix-sock.md"
"day-21-set-up-git-repository-on-storage-server.md"
"day-22-clone-git-repository-on-storage-server.md"
"day-23-fork-a-git-repository.md"
"day-24-git-create-branches.md"
"day-25-git-merge-branches.md"
"day-26-git-manage-remotes.md"
"day-27-git-revert-some-changes.md"
"day-28-git-cherry-pick.md"
"day-29-manage-git-pull-requests.md"
"day-30-git-hard-reset.md"
"day-31-git-stash.md"
"day-32-git-rebase.md"
"day-33-resolve-git-merge-conflicts.md"
"day-34-git-hook.md"
"day-35-install-docker-and-start-service.md"
"day-36-deploy-nginx-container.md"
"day-37-copy-file-to-docker-container.md"
"day-38-pull-docker-image.md"
"day-39-create-docker-image-from-container.md"
"day-40-docker-exec-operations.md"
"day-41-write-dockerfile.md"
"day-42-create-docker-network.md"
"day-43-docker-port-mapping.md"
"day-44-write-docker-compose-file.md"
"day-45-resolve-dockerfile-issues.md"
"day-46-deploy-app-on-docker.md"
"day-47-docker-python-app.md"
"day-48-deploy-pods-in-kubernetes.md"
"day-49-deploy-applications-with-kubernetes-deployments.md"
"day-50-set-resource-limits-in-kubernetes-pods.md"
"day-51-execute-rolling-updates-in-kubernetes.md"
"day-52-revert-deployment-to-previous-version-in-kubernetes.md"
"day-53-resolve-volume-mounts-issue-in-kubernetes.md"
"day-54-kubernetes-shared-volumes.md"
"day-55-kubernetes-sidecar-containers.md"
"day-56-deploy-nginx-web-server-on-kubernetes-cluster.md"
"day-57-print-environment-variables.md"
"day-58-deploy-grafana-on-kubernetes-cluster.md"
"day-59-troubleshoot-deployment-issues-in-kubernetes.md"
"day-60-persistent-volumes-in-kubernetes.md"
"day-61-init-containers-in-kubernetes.md"
"day-62-manage-secrets-in-kubernetes.md"
"day-63-deploy-iron-gallery-app-on-kubernetes.md"
"day-64-fix-python-app-deployed-on-kubernetes-cluster.md"
"day-65-deploy-redis-deployment-on-kubernetes.md"
"day-66-deploy-mysql-on-kubernetes.md"
"day-67-deploy-guest-book-app-on-kubernetes.md"
"day-68-set-up-jenkins-server.md"
"day-69-install-jenkins-plugins.md"
"day-70-configure-jenkins-user-access.md"
"day-71-configure-jenkins-job-for-package-installation.md"
"day-72-jenkins-parameterized-builds.md"
"day-73-jenkins-scheduled-jobs.md"
"day-74-jenkins-database-backup-job.md"
"day-75-jenkins-slave-nodes.md"
"day-76-jenkins-project-security.md"
"day-77-jenkins-deploy-pipeline.md"
"day-78-jenkins-conditional-pipeline.md"
"day-79-jenkins-deployment-job.md"
"day-80-jenkins-chained-builds.md"
"day-81-jenkins-multistage-pipeline.md"
"day-82-create-ansible-inventory-for-app-server-testing.md"
"day-83-troubleshoot-and-create-ansible-playbook.md"
"day-84-copy-data-to-app-servers-using-ansible.md"
"day-85-create-files-on-app-servers-using-ansible.md"
"day-86-ansible-ping-module-usage.md"
"day-87-ansible-install-package.md"
"day-88-ansible-blockinfile-module.md"
"day-89-ansible-manage-services.md"
"day-90-managing-acls-using-ansible.md"
"day-91-ansible-lineinfile-module.md"
"day-92-managing-jinja2-templates-using-ansible.md"
"day-93-using-ansible-conditionals.md"
"day-94-create-vpc-using-terraform.md"
"day-95-create-security-group-using-terraform.md"
"day-96-create-ec2-instance-using-terraform.md"
"day-97-create-iam-policy-using-terraform.md"
"day-98-launch-ec2-in-private-vpc-subnet-using-terraform.md"
"day-99-attach-iam-policy-for-dynamodb-access-using-terraform.md"
"day-100-create-and-configure-alarm-using-cloudwatch-using-terraform.md"
)

for f in "${files[@]}"; do
  path="$BASE/$f"

  if [ -f "$path" ]; then
    echo "SKIP (exists): $path"
  else
    touch "$path"
    echo "CREATED: $path"
  fi
done
